// <auto-generated />
using System;
using Kutuphane.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kutuphane.DAL.Migrations
{
    [DbContext(typeof(KutuphaneDbContext))]
    [Migration("20251209120221_s")]
    partial class s
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kutuphane.Model.Entity.Cinsiyet", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("CinsiyetAdi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Cinsiyetler");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CinsiyetAdi = "Erkek"
                        },
                        new
                        {
                            Id = (byte)2,
                            CinsiyetAdi = "Kadın"
                        },
                        new
                        {
                            Id = (byte)3,
                            CinsiyetAdi = "Belirtilmemiş"
                        });
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Dil", b =>
                {
                    b.Property<short>("DilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DilId"));

                    b.Property<string>("DilAdi")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.Property<string>("DilKodu")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.HasKey("DilId");

                    b.ToTable("Diller");

                    b.HasData(
                        new
                        {
                            DilId = (short)1,
                            DilAdi = "Türkçe",
                            DilKodu = "tr"
                        },
                        new
                        {
                            DilId = (short)2,
                            DilAdi = "İngilizce",
                            DilKodu = "en"
                        },
                        new
                        {
                            DilId = (short)3,
                            DilAdi = "Almanca",
                            DilKodu = "de"
                        },
                        new
                        {
                            DilId = (short)4,
                            DilAdi = "Fransızca",
                            DilKodu = "fr"
                        },
                        new
                        {
                            DilId = (short)5,
                            DilAdi = "İspanyolca",
                            DilKodu = "es"
                        },
                        new
                        {
                            DilId = (short)6,
                            DilAdi = "İtalyanca",
                            DilKodu = "it"
                        },
                        new
                        {
                            DilId = (short)7,
                            DilAdi = "Rusça",
                            DilKodu = "ru"
                        },
                        new
                        {
                            DilId = (short)8,
                            DilAdi = "Çince",
                            DilKodu = "zh"
                        },
                        new
                        {
                            DilId = (short)9,
                            DilAdi = "Japonca",
                            DilKodu = "ja"
                        },
                        new
                        {
                            DilId = (short)10,
                            DilAdi = "Arapça",
                            DilKodu = "ar"
                        },
                        new
                        {
                            DilId = (short)11,
                            DilAdi = "Portekizce",
                            DilKodu = "pt"
                        },
                        new
                        {
                            DilId = (short)12,
                            DilAdi = "Hollandaca",
                            DilKodu = "nl"
                        },
                        new
                        {
                            DilId = (short)13,
                            DilAdi = "İsveççe",
                            DilKodu = "sv"
                        },
                        new
                        {
                            DilId = (short)14,
                            DilAdi = "Fince",
                            DilKodu = "fi"
                        },
                        new
                        {
                            DilId = (short)15,
                            DilAdi = "Danca",
                            DilKodu = "da"
                        },
                        new
                        {
                            DilId = (short)16,
                            DilAdi = "Norveççe",
                            DilKodu = "no"
                        },
                        new
                        {
                            DilId = (short)17,
                            DilAdi = "Macarca",
                            DilKodu = "hu"
                        },
                        new
                        {
                            DilId = (short)18,
                            DilAdi = "Lehçe",
                            DilKodu = "pl"
                        },
                        new
                        {
                            DilId = (short)19,
                            DilAdi = "Çekçe",
                            DilKodu = "cs"
                        },
                        new
                        {
                            DilId = (short)20,
                            DilAdi = "Rumence",
                            DilKodu = "ro"
                        },
                        new
                        {
                            DilId = (short)21,
                            DilAdi = "Yunanca",
                            DilKodu = "el"
                        },
                        new
                        {
                            DilId = (short)22,
                            DilAdi = "Korece",
                            DilKodu = "ko"
                        },
                        new
                        {
                            DilId = (short)23,
                            DilAdi = "Hintçe",
                            DilKodu = "hi"
                        },
                        new
                        {
                            DilId = (short)24,
                            DilAdi = "Tayca",
                            DilKodu = "th"
                        },
                        new
                        {
                            DilId = (short)25,
                            DilAdi = "Vietnamca",
                            DilKodu = "vi"
                        },
                        new
                        {
                            DilId = (short)26,
                            DilAdi = "Endonezce",
                            DilKodu = "id"
                        },
                        new
                        {
                            DilId = (short)27,
                            DilAdi = "Malayca",
                            DilKodu = "ms"
                        },
                        new
                        {
                            DilId = (short)28,
                            DilAdi = "Filipince",
                            DilKodu = "tl"
                        });
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriId = 1,
                            KategoriAdi = "Roman"
                        },
                        new
                        {
                            KategoriId = 2,
                            KategoriAdi = "Hikaye"
                        },
                        new
                        {
                            KategoriId = 3,
                            KategoriAdi = "Şiir"
                        },
                        new
                        {
                            KategoriId = 4,
                            KategoriAdi = "Tarih"
                        },
                        new
                        {
                            KategoriId = 5,
                            KategoriAdi = "Bilim"
                        },
                        new
                        {
                            KategoriId = 6,
                            KategoriAdi = "Sanat"
                        },
                        new
                        {
                            KategoriId = 7,
                            KategoriAdi = "Felsefe"
                        },
                        new
                        {
                            KategoriId = 8,
                            KategoriAdi = "Çocuk"
                        },
                        new
                        {
                            KategoriId = 9,
                            KategoriAdi = "Gezi"
                        },
                        new
                        {
                            KategoriId = 10,
                            KategoriAdi = "Biyografi"
                        },
                        new
                        {
                            KategoriId = 11,
                            KategoriAdi = "Kişisel Gelişim"
                        },
                        new
                        {
                            KategoriId = 12,
                            KategoriAdi = "Psikoloji"
                        },
                        new
                        {
                            KategoriId = 13,
                            KategoriAdi = "Ekonomi"
                        },
                        new
                        {
                            KategoriId = 14,
                            KategoriAdi = "Politika"
                        },
                        new
                        {
                            KategoriId = 15,
                            KategoriAdi = "Din"
                        },
                        new
                        {
                            KategoriId = 16,
                            KategoriAdi = "Mitoloji"
                        },
                        new
                        {
                            KategoriId = 17,
                            KategoriAdi = "Fantastik"
                        },
                        new
                        {
                            KategoriId = 18,
                            KategoriAdi = "Bilim Kurgu"
                        },
                        new
                        {
                            KategoriId = 19,
                            KategoriAdi = "Macera"
                        },
                        new
                        {
                            KategoriId = 20,
                            KategoriAdi = "Korku"
                        },
                        new
                        {
                            KategoriId = 21,
                            KategoriAdi = "Polisiye"
                        },
                        new
                        {
                            KategoriId = 22,
                            KategoriAdi = "Dram"
                        },
                        new
                        {
                            KategoriId = 23,
                            KategoriAdi = "Komedi"
                        },
                        new
                        {
                            KategoriId = 24,
                            KategoriAdi = "Aşk"
                        },
                        new
                        {
                            KategoriId = 25,
                            KategoriAdi = "Dünya Klasikleri"
                        },
                        new
                        {
                            KategoriId = 26,
                            KategoriAdi = "Edebiyat"
                        },
                        new
                        {
                            KategoriId = 27,
                            KategoriAdi = "Sağlık"
                        },
                        new
                        {
                            KategoriId = 28,
                            KategoriAdi = "Yemek"
                        },
                        new
                        {
                            KategoriId = 29,
                            KategoriAdi = "Spor"
                        },
                        new
                        {
                            KategoriId = 30,
                            KategoriAdi = "Diğer"
                        });
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Kitap", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapId"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("BasimYili")
                        .HasColumnType("int");

                    b.Property<short>("DilId")
                        .HasColumnType("smallint");

                    b.Property<string>("ISBN")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("SayfaSayisi")
                        .HasColumnType("int");

                    b.Property<int>("Stok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("YayineviId")
                        .HasColumnType("int");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.HasKey("KitapId");

                    b.HasIndex("DilId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.KitapKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KitapId");

                    b.ToTable("KitapKategori");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Odunc", b =>
                {
                    b.Property<int>("OduncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OduncId"));

                    b.Property<DateTime>("AlisTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int?>("TeslimAlanPersonelId")
                        .HasColumnType("int");

                    b.Property<int>("TeslimEdenPersonelId")
                        .HasColumnType("int");

                    b.Property<bool>("TeslimEdildi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("OduncId");

                    b.HasIndex("KitapId");

                    b.HasIndex("TeslimAlanPersonelId");

                    b.HasIndex("TeslimEdenPersonelId");

                    b.HasIndex("UyeId");

                    b.ToTable("Oduncler");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<byte>("CinsiyetId")
                        .HasColumnType("tinyint");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("PersonelId");

                    b.HasIndex("CinsiyetId");

                    b.ToTable("Personeller");

                    b.HasData(
                        new
                        {
                            PersonelId = 1,
                            Ad = "Necati",
                            CinsiyetId = (byte)1,
                            KullaniciAdi = "neco",
                            Sifre = "MTIzNDU=",
                            Soyad = "Dalar"
                        },
                        new
                        {
                            PersonelId = 2,
                            Ad = "Necoş",
                            CinsiyetId = (byte)1,
                            KullaniciAdi = "neci",
                            Sifre = "MTIz",
                            Soyad = "Dalmaz"
                        });
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Uye", b =>
                {
                    b.Property<int>("UyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyeId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("AdresDetay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("CinsiyetId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("TcPass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.HasKey("UyeId");

                    b.HasIndex("CinsiyetId");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Yayinevi", b =>
                {
                    b.Property<int>("YayineviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YayineviId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("KurulusYili")
                        .HasColumnType("int");

                    b.HasKey("YayineviId");

                    b.ToTable("Yayinevleri");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.YayineviKitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DonemBaslangici")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DonemBitisi")
                        .HasColumnType("datetime");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int>("YayineviId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.HasIndex("YayineviId");

                    b.ToTable("YayineviKitaplari");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Yazar", b =>
                {
                    b.Property<int>("YazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("YazarID");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.YazarKitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.HasIndex("YazarId");

                    b.ToTable("YazarKitaplari");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Kitap", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Dil", "Diller")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diller");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.KitapKategori", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Kategori", "Kategori")
                        .WithMany("KitapKategoriler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Model.Entity.Kitap", "Kitap")
                        .WithMany("KitapKategoriler")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kitap");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Odunc", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Kitap", "Kitap")
                        .WithMany("Oduncler")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kutuphane.Model.Entity.Personel", "TeslimAlanPersonel")
                        .WithMany("TerslimAlinanlar")
                        .HasForeignKey("TeslimAlanPersonelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kutuphane.Model.Entity.Personel", "TeslimEdenPersonel")
                        .WithMany("TeslimEdilenler")
                        .HasForeignKey("TeslimEdenPersonelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Kutuphane.Model.Entity.Uye", "Uye")
                        .WithMany("Oduncler")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("TeslimAlanPersonel");

                    b.Navigation("TeslimEdenPersonel");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Personel", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Cinsiyet", "Cinsiyet")
                        .WithMany("Personeller")
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinsiyet");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Uye", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Cinsiyet", "Cinsiyet")
                        .WithMany()
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cinsiyet");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.YayineviKitap", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Kitap", "Kitap")
                        .WithMany("KitapYayinevleri")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Model.Entity.Yayinevi", "Yayinevi")
                        .WithMany("YayineviKitaplari")
                        .HasForeignKey("YayineviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Yayinevi");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.YazarKitap", b =>
                {
                    b.HasOne("Kutuphane.Model.Entity.Kitap", "Kitap")
                        .WithMany("KitapYazarlari")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Model.Entity.Yazar", "Yazar")
                        .WithMany("YazarKitaplari")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Cinsiyet", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Kategori", b =>
                {
                    b.Navigation("KitapKategoriler");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Kitap", b =>
                {
                    b.Navigation("KitapKategoriler");

                    b.Navigation("KitapYayinevleri");

                    b.Navigation("KitapYazarlari");

                    b.Navigation("Oduncler");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Personel", b =>
                {
                    b.Navigation("TerslimAlinanlar");

                    b.Navigation("TeslimEdilenler");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Uye", b =>
                {
                    b.Navigation("Oduncler");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Yayinevi", b =>
                {
                    b.Navigation("YayineviKitaplari");
                });

            modelBuilder.Entity("Kutuphane.Model.Entity.Yazar", b =>
                {
                    b.Navigation("YazarKitaplari");
                });
#pragma warning restore 612, 618
        }
    }
}
